version: "3.8"
services:
  bot:
    build:
      context: ./src
      dockerfile: ./bot/Dockerfile
    image: andylolu24/yourmum-bot:latest
    environment:
      - API_PORT
      - ENV
      - DISCORD_BOT_TOKEN
      - DISCORD_DEV_BOT_TOKEN
    depends_on:
      - api
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 50m
  api:
    build:
      context: ./src
      dockerfile: ./api/Dockerfile
    image: andylolu24/yourmum-api:latest
    environment:
      - MODULE_NAME=api.main
      - MAX_WORKERS=1
    network_mode: host
    depends_on:
      - corenlp
      - languagetools
    deploy:
      resources:
        limits:
          memory: 200m
  corenlp:
    image: "nlpbox/corenlp"
    environment:
      - JAVA_XMX=200m
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 200m
  languagetools:
    image: "erikvl87/languagetool"
    environment:
      - Java_Xmx=200m
      - Java_Xms=50m
    ports:
      - 8010:8010
    deploy:
      resources:
        limits:
          memory: 250m
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    command:
      - "--web.config.file=/etc/prometheus/web.yml"
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "${PROM_PATH}/prometheus/config.secret.yml:/etc/prometheus/prometheus.yml"
      - "${PROM_PATH}/prometheus/web.secret.yml:/etc/prometheus/web.yml"
    deploy:
      resources:
        limits:
          memory: 50m
