#cloud-config
mounts:
  - [ /swapfile, none, swap, defaults, 0, 0 ]

runcmd:
  - sudo ufw disable
  - sudo fallocate -l 1G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - sudo sed -i 's/\#\?MaxSessions .\+/MaxSessions 500/' /etc/ssh/sshd_config
  - sudo service ssh restart
