# docs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"

    static_configs:
      - targets: ["localhost:$API_PORT"]

remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: "$GRAFANA_CLD_USR"
      password: "$GRAFANA_CLD_PWD"
