name: Build docker image, push to docker hub, deploy to server

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    env:
      API_PORT: 80

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy
        run: make do-prod-deploy
