name: Build docker image, push to docker hub, deploy to EC2

on: 
  push:
    branches:
      - master

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Start
      run: |-
        echo "Starting setup..."

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Terraform and login to Terraform Cloud
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init
      run: |-
        make terraform-init

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        known_hosts: 'placeholder'

    - name: Try SSH with EC2 instance
      run: |-
        make ssh-add-known-host
        make ssh-ec2 CMD="pwd"

    - name: Build
      run: |-
        make docker-build
    
    - name: Publish
      run: |-
        make docker-tag
        make docker-push

    - name: Deploy
      run: |-
        make deploy
