name: Build docker image, push to docker hub, deploy to EC2

on: 
  push:
    tags:
      - "*"

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Terraform and login to Terraform Cloud
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform init
      run: |-
        make terraform-init

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        known_hosts: 'placeholder'

    - name: SSH add known hosts
      run: |-
        make ssh-add-known-host

    - name: Try SSH to instance
      run: |-
        make ssh-instance CMD="pwd"

    - name: Build
      run: |-
        make docker-build

    - name: Push
      run: |-
        make docker-push

    - name: Deploy
      run: |-
        make deploy
