name: Build docker image, push to docker hub, deploy to server

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    env:
      API_PORT: 80

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Setup
        run: doctl serverless install

      - name: Deploy
        env:
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          LOGTAIL_HTTP_SOURCE_TOKEN: ${{ secrets.LOGTAIL_HTTP_SOURCE_TOKEN }}
        run: |
          touch .prod.env
          make do-prod-deploy
